/**
 * Content model for the portfolio.
 *
 * Every word and number the site renders lives under content/ — never inline in
 * a component. Ported from lib/data/portfolio_data.dart and
 * lib/utils/constants.dart of the Flutter original, reconciled against
 * Mohamed_Ramadan_CV_EN.pdf.
 */

export type Project = {
  slug: string;
  title: string;
  /** One-line summary used on cards. */
  description: string;
  /** Full paragraph used in the expanded / flagship treatment. */
  longDescription: string;
  technologies: string[];
  tags: string[];
  /** Display country, uppercased by the UI. */
  country: string;
  category: string;
  /** The outcome line — a number wherever one is defensible. */
  achievement: string;
  links: { appStore?: string; playStore?: string; github?: string; website?: string };
  /**
   * Android application id. Rendered as visible text, not only in structured
   * data: a literal identifier search is matched against the served HTML.
   * Early apps carry client-chosen namespaces; see `publisherNamespace`.
   */
  bundleId?: string;
  /** Slug under public/images/ with generated AVIF/WebP variants, if any. */
  image?: { slug: string; width: number; height: number; alt: string };
  /** Supplied brand assets and how they are plated. See ProjectMedia. */
  media?: ProjectMedia;
  /** Leads the section in the big panel. Exactly one project carries it. */
  flagship?: boolean;
  /** Shown where store links would be, when there are none. */
  linkStatus?: string;
  /** Private client delivery: no public listing, gets its own card treatment. */
  isPrivate?: boolean;
  /** Extra detail bullets, shown only where the layout has room. */
  highlights?: string[];
};

export type Experience = {
  slug: string;
  company: string;
  position: string;
  location: string;
  country: string;
  /** Free-form display strings, e.g. "January 2025". */
  startDate: string;
  endDate: string;
  /** ISO YYYY-MM, for sorting and <time> elements. */
  start: string;
  end: string | null;
  isCurrent: boolean;
  engagement?: string;
  description: string;
  achievements: string[];
  technologies: string[];
};

export type SkillGroup = {
  label: string;
  items: string[];
  /** At most one group may be highlighted — one copper accent per viewport. */
  highlighted?: boolean;
};


/**
 * How a project's supplied imagery is presented.
 *
 * DESIGN-SYSTEM §5.2 defines four plates, and one rule above all of them: no
 * supplied asset ever touches the page background directly. Containment only —
 * no blend modes, no background removal. Every `file` names a slug under
 * public/images/projects/, generated by `npm run images`.
 */
export type ProjectMedia = {
  /** Store icon, rendered inset in the 96px tile. */
  icon?: {
    file: string;
    /** Transparent sources get padding and no radius — there is no field to chip. */
    transparent?: boolean;
  };
  /**
   * - `device` — a capture seated whole on ink, bezel drawn by the frame.
   * - `field`  — an asset with its own brand ground, full-bleed via `cover`.
   * - `promo`  — a store promo shown whole via `contain`, never cropped.
   * - `icon`   — no capture; the icon tile carries the card.
   */
  plate: "device" | "field" | "promo" | "icon";
  asset?: {
    file: string;
    width: number;
    height: number;
    alt: string;
    /**
     * False when the source already includes its own device frame — drawing a
     * second bezel around a bezel looks like a mistake.
     */
    bezel?: boolean;
  };
  /** 1:1 posts. A different aspect, so they get their own strip. */
  social?: { file: string; width: number; height: number; alt: string }[];
};
