/**
 * Renders everything in content/ as one readable Markdown brief.
 *
 * Design tools and design sessions cannot read TypeScript modules, and a zip of
 * .ts files is a poor brief. This flattens the same source of truth into prose
 * so a designer works from the real copy rather than a reconstruction.
 *
 *   npm run brief   ->  design/CONTENT-BRIEF.md
 *
 * Compiled to CommonJS in a temp dir first, because content/ uses
 * extensionless imports that Node's type stripping will not resolve.
 */
import { writeFileSync } from "node:fs";
import { site, contact, socials, metrics, navSections, education } from "../content/site";
import { projects } from "../content/projects";
import { experiences } from "../content/experience";
import { skillGroups, marqueeItems } from "../content/skills";
import * as copy from "../content/copy";

const out: string[] = [];
const w = (s = "") => out.push(s);

w("# Content brief — every word the site renders");
w();
w("Generated from `content/` by `npm run brief`. **Do not edit this file** —");
w("edit the modules under `content/` and regenerate. Use this copy verbatim;");
w("nothing here is a placeholder.");
w();
w("---");
w();
w("## Identity");
w();
w(`- **Name:** ${site.name} (short: ${site.shortName})`);
w(`- **Title:** ${site.title} — ${site.subtitle}`);
w(`- **Location:** ${site.location} (${site.timezone})`);
w(`- **Email:** ${contact.email} · **Phone:** ${contact.phoneDisplay}`);
w(`- **Résumé:** ${contact.resumeUrl}`);
w(`- **Links:** ${socials.map((s) => `${s.label} → ${s.handle} (${s.url})`).join(" · ")}`);
w(`- **Headline numbers:** ${metrics.yearsExperience} years · ${metrics.appsLiveOnBothStores} apps on both stores · ${metrics.teams} teams · ${metrics.countries} countries`);
w(`- **Nav:** ${navSections.map((s) => s.label).join(" · ")}`);
w();
w("### Education & certifications");
w();
education.forEach((e) => w(`- ${e}`));
w();
w("---");
w();
w("## Hero");
w();
w(`- Status chip: **${copy.hero.status}** · ${copy.hero.place}`);
w(`- Headline (3 lines, line ${copy.hero.headlineAccentIndex + 1} carries the copper accent):`);
copy.hero.headline.forEach((l, i) =>
  w(`  ${i + 1}. ${l}${i === copy.hero.headlineAccentIndex ? "  ← copper" : ""}`),
);
w(`- Intro: ${copy.hero.intro}`);
w(`- CTAs: **${copy.hero.primaryCta.label}** (primary) · ${copy.hero.secondaryCta.label} (ghost) · ${copy.hero.resumeCta.label} (text link)`);
w(`- Panel "${copy.hero.trackRecordLabel}" — three metrics that count up once in view:`);
copy.hero.trackRecord.forEach((m) => w(`  - **${m.value}${m.suffix}** — ${m.label}`));
w(`- Plus a live "${copy.hero.viewsLabel}" figure streamed from Firebase (real number, changes on every load).`);
w();
w("## Tech marquee");
w();
w(`${marqueeItems.length} items, infinite horizontal strip, pauses on hover:`);
w();
w(marqueeItems.join(" · "));
w();
w("---");
w();
w(`## About — eyebrow \`${copy.about.eyebrow}\``);
w();
w(`Headline (3 lines): ${copy.about.headline.join(" / ")}`);
w();
w(`**Lede (set larger):** ${copy.about.lede}`);
w();
copy.about.body.forEach((p) => {
  w(p);
  w();
});
w("Metric grid (4 cells, first is copper):");
w();
copy.about.stats.forEach((s) => w(`- **${s.value}** — ${s.label}`));
w();
w("---");
w();
w(`## Experience — eyebrow \`${copy.experienceCopy.eyebrow}\`, headline "${copy.experienceCopy.headline}"`);
w();
w(`${experiences.length} roles. Rows expand; the current one opens by default.`);
w("Badge on the current role reads `" + copy.experienceCopy.currentBadge + "`.");
w();
w("> **Note for layout:** these engagements OVERLAP heavily — four ran");
w("> concurrently through 2024 (Demeter, Ebdda, Arcit-AI, Eleven Stars), most");
w("> of them remote and part-time. A strictly linear timeline will misrepresent");
w("> this. Either show the concurrency deliberately or avoid a time axis.");
w();
experiences.forEach((r, i) => {
  w(`### ${String(i + 1).padStart(2, "0")}. ${r.position} — ${r.company}`);
  w();
  w(`\`${r.startDate} — ${r.endDate}\` · ${r.location}${r.engagement ? ` · ${r.engagement}` : ""}${r.isCurrent ? " · **CURRENT**" : ""}`);
  w();
  w(r.description);
  w();
  r.achievements.forEach((a) => w(`- ${a}`));
  w();
  w(`*Tech:* ${r.technologies.join(" · ")}`);
  w();
});
w("---");
w();
w(`## Projects — eyebrow \`${copy.projectsCopy.eyebrow}\`, headline "${copy.projectsCopy.headline}"`);
w();
w(`${projects.length} projects. The first is the flagship and is the only one with a real screenshot.`);
w();
projects.forEach((p, i) => {
  w(`### ${String(i + 1).padStart(2, "0")}. ${p.title}${i === 0 ? "  — FLAGSHIP" : ""}${p.isPrivate ? "  — PRIVATE CLIENT, NO STORE LINKS" : ""}`);
  w();
  w(`*${p.category} · ${p.country}*`);
  w();
  w(`**Card line:** ${p.description}`);
  w();
  w(`**Long form:** ${p.longDescription}`);
  w();
  w(`**Outcome:** ${p.achievement}`);
  w();
  w(`*Tech:* ${p.technologies.join(" · ")}`);
  w();
  if (p.highlights) {
    w("Detail bullets (currently truncated to 2 on the card — a detail view could show all):");
    w();
    p.highlights.forEach((h) => w(`- ${h}`));
    w();
  }
  if (p.isPrivate) {
    w(`Needs a deliberate treatment reading "${copy.projectsCopy.privateLabel}" — not an empty slot where the store buttons would be.`);
  } else {
    w(`Links: ${p.links.appStore ? "App Store" : ""}${p.links.appStore && p.links.playStore ? " · " : ""}${p.links.playStore ? "Google Play" : ""}`);
  }
  if (p.image) w(`Image: \`public/images/${p.image.slug}/\` — ${p.image.width}×${p.image.height} portrait phone screenshot.`);
  w();
});
w("---");
w();
w(`## Skills — eyebrow \`${copy.skillsCopy.eyebrow}\`, headline "${copy.skillsCopy.headline}"`);
w();
w(copy.skillsCopy.blurb);
w();
w(`${skillGroups.length} groups, ${skillGroups.reduce((n, g) => n + g.items.length, 0)} capabilities. Group sizes are uneven — 5, 5, 9, 11, 7, 10 — so any layout that assumes equal cells will break.`);
w();
skillGroups.forEach((g) => {
  w(`**${g.label}**${g.highlighted ? "  ← the one highlighted group" : ""} (${g.items.length})`);
  w();
  w(g.items.join(" · "));
  w();
});
w("---");
w();
w(`## Contact — eyebrow \`${copy.contactCopy.eyebrow}\``);
w();
w(`Headline: ${copy.contactCopy.headline.join(" / ")} (the word "build?" is copper)`);
w();
w(copy.contactCopy.blurb);
w();
w(`- CTAs: **${contact.email}** (primary) · ${contact.phoneDisplay} (ghost, mono)`);
w(`- Link panel: ${socials.map((s) => `${s.label} → ${s.handle}`).join(" · ")}, plus a résumé download row`);
w(`- Availability block: label \`${copy.contactCopy.availabilityLabel}\`, jade dot, "${copy.contactCopy.availability}"`);
w(`- Form eyebrow: "${copy.contactCopy.formEyebrow}"`);
w("- Five fields, three required:");
Object.entries(copy.contactCopy.fields).forEach(([k, f]) =>
  w(`  - **${f.label}** — placeholder "${f.placeholder}"${["name", "email", "message"].includes(k) ? " · required" : ""}`),
);
w(`- Button: **${copy.contactCopy.submit}** (sending: "${copy.contactCopy.submitting}")`);
w(`- Success: "${copy.contactCopy.success}"`);
w(`- Failure: "${copy.contactCopy.failure}"`);
w("- Inline errors need designing — every required field has a message and a rose border state.");
w();
w("## Footer");
w();
w(`Mark + "${site.shortName} © <year> · ${copy.footerCopy.builtWith}" · "${site.designCodename} ${site.designVersion} · <n> views" · "${copy.footerCopy.backToTop} ↑"`);
w();

writeFileSync("design/CONTENT-BRIEF.md", out.join("\n"));
console.log(`design/CONTENT-BRIEF.md — ${out.length} lines`);
